apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: fplugin
  name: fplugin
  namespace: default
spec:
  selector:
    matchLabels:
      app: fplugin
  template:
    metadata:
      labels:
        app: fplugin
    spec:
      containers:
      - image: gcr.io/fantasy-218701/fplugin:7ea2b4d05e428c93672bb6bdad91352398539b05
        livenessProbe:
          httpGet:
            path: /alive
            port: 8080
        name: fplugin
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
