apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fplugin
  annotations:
    kubernetes.io/ingress.global-static-ip-name: fplugin-staging
  labels:
    app: fplugin
spec:
  backend:
    serviceName: fplugin
    servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fplugin
  namespace: default
  labels:
    app: fplugin
spec:
  type: NodePort
  selector:
    app: fplugin
  ports:
  - port: 8080
    targetPort: 8080
